config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 resources :todos
 root "todos#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :title, :due_date, :description

  # 判斷是否能夠刪除
  # 判斷條件可能有很多，所以將各項判斷分拆到 private method
  def can_destroy?
    # 沒過期的話，回傳 ture=可刪除
    !overdue?
  end

  # 宣告以下為private method
  # private_method 無法被直接使用
  # ‘todo。overdue？’會跳出錯誤：NoMethodError: private method 'overdue?'
  # 可以用Ruby原生的kernel#send來呼叫private_method: todo.send(:overdue?)

  private

  #如果due_date比今天小，則回傳 true=過期
  def overdue?
    due_date < Date.today
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
#備註事項：
class TodosController < ApplicationController
  before_action :set_todo, :only => [:show, :edit, :update, :destroy]

  def index
    @todos = Todo.order(due_date: :asc)
    #依到期日（due_date）近到遠，取得todos
  end

  def new
    @todo = Todo.new
  end

  def create
    #依傳入參數new一個Todo實例
    @todo = Todo.new(todo_params)
    #如果驗證成功，則儲存並回到列表頁，告知成功新增
    #如果驗證失敗，則不儲存，並保留已填入資訊，回到new，繼續填寫
    if @todo.save
      #跳出通知訊息，告知成功新增
      flash[:notice] = 'Todo-list was successfully added!'
      #重新發出request，導往列表頁。對瀏覽器來說會重整頁面
      redirect_to todos_url
    else
      #當驗證失敗時，將@todo傳入new.html.erb做render
      #以達成體驗上：「保留已填寫資料，讓使用者可以繼續填寫錯誤的部分」
      render :action => :new
    end
  end

  #彷彿沒有內容，是因為原先次action內的代碼：
  # def show
  #   @todo = Todo.find(params[:id])
  # end
  #此段的作用已被 before_action :find_todo 取代 

  def update
    # @todo = Todo.find(params[:id])
    #此行的作用已被 before_action :find_todo 取代

    #如果驗證成功，則更新，並回到列表頁，告知成功更新
    #如果驗證失敗，則不更新，並保留已填寫的資料，回到edit,繼續填寫
    if @todo.update_attributes(todo_params)
      #經過find id之後，再透過update_attributes,將更改過的資料回送至資料庫
      #跳出通知訊息，告知成功更新
      flash[:notice] = 'Todo-list was successfully updated!'
      #重新發出request,導往列表頁。對瀏覽器來說會重整頁面
      redirect_to todo_url(@todo)
    else
      #當驗證失敗時，將@todo傳入edit.html.erb做render
      #以達成體驗上：「保留已填寫資料，讓使用者可以繼續填寫錯誤的部分」
      reder :action => :edit
    end
  end

  def destroy
    # @todo = Todo.find(params[:id])
    # 此行的作用已被before_action :find_todo 取代

    # Todo#can_destroy?定義在todo.rb裡
    # 如果可以刪除，則刪除，並回到列表頁，告知刪除成功
    # 如果不允許刪除，則回到列表頁，並告知過期
    if @todo.can_destroy?
      @todo.destroy
      # 跳出警告訊息，告知成功刪除
      flash[:notice] = 'Task was successfully deleted!!'
      # 重新發出request，導往列表頁。對瀏覽器來說會重整頁面
      redirect_to todos_url
    else
      # 跳出警告訊息，告知過期
      flash[:alert] = 'Task is overdue, can not be deleted! Try to finish it! You can make it!!'
      # 重新發出request，導往列表頁。對瀏覽器來說會重整頁面
      redirect_to todos_url
    end
  end

  private

  # 在#edit, #update, #destroy都有找到特定 ID todo的需求
  # 於是可以提取出 before_action :find_todo
  # 在以上三個action執行之前，先找出特定 ID 的 todo
  # 方法命名慣用（find_todo)，但是可自行決定，所以用（set_todo）

  def set_todo
    @todo = Todo.find(params[:id])
  end

  # Term: strong parameters, > Rails 4 only.
  # 基於安全性考量，不可以直接將未經允許 (permit) 的參數導入 model做新增或修改
  # 可視需求在各 controller 分開獨立指定允許的內容
  # 方法命名（todo_params)只是慣用，實際上可自行決定

  def todo_params
    # params 變數是Rails在消化完 http request 後，所留下的 controller 常用參數群
    # #require 方法裡的 symbol 與 form 送回的物件名稱相同
    # #permit 方法裡的 symbol 與 form 送回的物件欄位名稱相同
    params.require(:todo).permit(:title, :due_date, :description)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ToDoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <% if flash.present? %>

      <div class="flashmsg">
        <p style= "color:green"><%= flash[:notice] %></p>
        <p style= "color:red"><%= flash[:alert] %></p>
      </div>

    <%end%>
    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<div class="errormsg">
  <% if @todo.errors.present? %>
    <ul>
      <% @todo.errors.each do |error, message| %>
        <li> <%= "#{error.capitalize} #{message}" %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div class="itembox">
    <%= form_for @todo do |f| %>
      <%= f.label :title, 'Title' %>
      <br>
      <%= f.text_field :title %>
      <br>
      <%= f.label :due_date, 'D-date' %>
      <br>
      <%= f.text_field :due_date %>
      <br>
      <%= f.label :description, 'Description' %>
      <br>
      <%= f.text_area :description %>
      <br>

      <div class="item_btn">
      <%= f.submit button, class: 'btn btn-success' %>
      <%= link_to 'Back', :back, class: 'btn btn-primary'%>
      </div>
    <% end %>
</div>

app/views/todos/edit.html.erb
<%= render :partial => "form", locals: {button: 'Update'} %>

app/views/todos/index.html.erb
  <div class= "listbox">
    <h1> My Todo List</h1>

      <div class ="list">
        <ul>
          <% @todos.each do |todo| %>
            <li>
              <p class="due_date"> Due date : <%= todo.due_date %></p>
              <p class="title"> Task : <%= todo.title %></p>
              <p class="functionbar"><%= link_to 'Detail', todo_path(todo) %>
              <%= link_to 'Edit', edit_todo_path(todo) %>
              <%= link_to 'Delete', todo_path(todo), method: :delete, data:{ confirm: "Are you  sureeeee?"} %></p>       
            </li>
          <% end %>  
        </rl>
      </div>

      <div class="addbtn">
        <%= link_to 'ADD LIST', new_todo_path, class: 'btn btn-success'%>
      </div>
  </div>

app/views/todos/new.html.erb
<%= render :partial => "form", locals: { button: 'SUBMIT' } %>

app/views/todos/show.html.erb
<div class="itembox">
  <p class="due_date"> Due Date: <%= @todo.due_date %></p>
  <p class="title"> Task: <%= @todo.title %></p>
  <P> Note: <%= simple_format(@todo.description) %></P>

  <div class= "itembox_btn">
    <%= link_to 'Edit', edit_todo_path(@todo), class: 'btn btn-warning'  %>
    <%= link_to 'Back to index', todos_path, class: 'btn btn-primary' %>
  </div>
</div>